services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      RAM_SIZE: "8G"
      USERNAME: "RandomHooman12"
      PASSWORD: "@Password123456"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - /tmp/storage:/storage
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
