services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "sonoma"
      RAM_SIZE: "8G"
    devices:
      - /dev/kvm
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /tmp/storage:/storage
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
